### ISSUE TITLE
Install instructions don't work (for me)

### ISSUE THREAD

**Issue by mryanprice** [bombsimon/wsl#129] opened 2023-04-20 17:26 UTC
i'm on macos

```
$ go get github.com/bombsimon/wsl/v4/cmd/...
go: downloading github.com/bombsimon/wsl v1.2.8
go: module github.com/bombsimon/wsl@upgrade found (v1.2.8), but does not contain packages matching github.com/bombsimon/wsl/v4/cmd/...
```

This does seem to work:
```
 go install github.com/bombsimon/wsl/cmd/...@latest
```

**Comment by bombsimon** [comment] 2023-04-20 18:37
Yes, sorry about that! Duplicate of #127 so I'm closing this. I'll update the readme to avoid more confusion until I finish a proper v4.0 release.

**Closed by bombsimon** 2023-04-20 18:37 UTC
