### ISSUE TITLE
Incorrect check of assignment usage in loop and if statements

### ISSUE THREAD

**Issue by dm-godsend** [bombsimon/wsl#119] opened 2023-02-21 00:43 UTC
If assignment is not on the first line of the loop/if-statement, linter doesn't work correctly.
<img width="813" alt="image" src="https://user-images.githubusercontent.com/56953370/220217991-14a280a3-c16a-47cb-8dc7-007411f4c86c.png">

**Comment by bombsimon** [comment] 2023-02-21 08:39
Thanks for the issue. This looks like a duplicate of #50, please re-open if I'm wrong.

**Closed by bombsimon** 2023-02-21 08:39 UTC
